### ISSUE TITLE
‘jerichojars’ is not available for package ‘jericho’

### ISSUE THREAD

**Issue by jrosen48** [hrbrmstr/2017-year-in-review#1]
When using `devtools::install_github("hrbrmstr/jericho")`, the following error is returned:

```
ERROR: dependency ‘jerichojars’ is not available for package ‘jericho’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/jericho’
Installation failed: Command failed (1)
```

May be minor but wanted to note in case there was an easy fix (or I'm doing something incorrectly).

**Comment by hrbrmstr** [comment]
Thx for taking the Rmd for a spin/knit and also for taking the time to file an issue/question!

Darnit. The devtools install github thing defintely picks up the `Remotes` field on my system. 

Please do:

    devtools::install_github("hrbrmstr/jerichojars")

and that should clear that up.

**Comment by hrbrmstr** [comment]
I updated the Rmd to reflect this. If you try it again and it works, I'll close the issue.

**Comment by jrosen48** [comment]
Works! Sorry for the delay :)
